Repository pytorch-ignite/code-generator, pull requests merged in 2021-05, with the labels that each got.

#107 ci: change lint job
  .github/workflows/ci.yml
  package.json
Labels: ci

#108 feat: add sidebar for left pane for mobile
  src/App.vue
  src/components/NavBar.vue
  src/components/PaneLeft.vue
  src/components/PaneSplit.vue
Labels: enhancement

#109 feat: show thanksgiving message after download
  src/components/IconDiscord.vue
  src/components/IconDownload.vue
  src/components/IconGitHub.vue
  src/components/IconTwitter.vue
  src/components/NavBar.vue
  src/components/PaneSplit.vue
Labels: enhancement

#106 feat: add copy button for code
  src/components/CodeBlock.vue
Labels: enhancement

#111 feat: template setup and render with ejs
  .env
  .gitignore
  netlify.toml
  package.json
  pnpm-lock.yaml
  scripts/getCommit.js
  src/components/NavBar.vue
  src/components/PaneLeft.vue
  src/components/PaneRight.vue
  src/components/TabModel.vue
  src/components/TabTemplates.vue
  src/metadata/README.md
  src/metadata/models/text.json
  src/metadata/models/vision.json
  src/store.js
  src/templates/datasets.py
  src/templates/main.py
  src/templates/models.py
  src/templates/template-common/utils.py
  src/templates/template-vision-classification/README.md
  src/templates/template-vision-classification/config.json
  src/templates/template-vision-classification/data.py
  src/templates/template-vision-classification/main.py
  src/templates/template-vision-classification/model.py
  src/templates/template-vision-classification/requirements.txt
  src/templates/template-vision-classification/trainers.py
  src/templates/template-vision-classification/utils.py
  src/templates/templates.json
  src/templates/trainers.py
  src/templates/utils.py
Labels: enhancement

#112 feat: show git commit on nav bar
  .env
  index.html
  scripts/getCommit.js
  src/App.vue
  src/components/NavBar.vue
  src/store.js
Labels: enhancement

#113 chore: change .env to .env.local
  .env
  scripts/getCommit.js
Labels: enhancement

#114 ci: add copies of files up-to-date checking
  .github/workflows/ci.yml
  netlify.toml
  package.json
  scripts/check_copies.py
Labels: enhancement

#115 refactor: extract footer into Footer component
  src/App.vue
  src/assets/netlify-color-accent.svg
  src/components/Footer.vue
Labels: enhancement

#116 fix: restructure and add more Ignite core features
  src/App.vue
  src/components/CodeBlock.vue
  src/components/FormCheckbox.vue
  src/components/FormInput.vue
  src/components/FormRadio.vue
  src/components/FormSelect.vue
  src/components/NavBar.vue
  src/components/PaneRight.vue
  src/components/TabHandlers.vue
  src/components/TabLoggers.vue
  src/components/TabTraining.vue
  src/metadata/metadata.json
  src/metadata/training.json
  src/metadata/utils.json
  src/store.js
Labels: enhancement

#117 chore: get commit in vite config
  package.json
  scripts/getCommit.js
  src/components/NavBar.vue
  src/metadata/metadata.json
  src/store.js
  vite.config.js
Labels: enhancement

#120 fix: make UI consistent across browsers
  .gitignore
  src/components/FormSelect.vue
  src/components/Instruction.vue
  src/components/PaneLeft.vue
  src/components/PaneRight.vue
  src/components/PaneSplit.vue
Labels: bug

#121 feat: add error and info message box
  src/components/CodeBlock.vue
  src/components/Message.vue
  src/components/NavBar.vue
  src/components/PaneLeft.vue
  src/store.js
Labels: enhancement

#122 chore: comment another watch usage, timeout message box
  src/components/Message.vue
  src/components/NavBar.vue
  src/store.js
Labels: enhancement

#123 chore: update contributing
  .github/run_code_style.sh
  CONTRIBUTING.md
  package.json
  src/store.js
  src/templates/template-vision-classification/main.py
  src/templates/templates.json
Labels: documentation

#119 feat(template): add dcgan template
  .github/workflows/ci.yml
  CONTRIBUTING.md
  scripts/check_copies.py
  src/templates/template-common/config.yaml
  src/templates/template-common/main.py
  src/templates/template-common/requirements.txt
  src/templates/template-vision-dcgan/README.md
  src/templates/template-vision-dcgan/config.yaml
  src/templates/template-vision-dcgan/data.py
  src/templates/template-vision-dcgan/main.py
  src/templates/template-vision-dcgan/model.py
  src/templates/template-vision-dcgan/requirements.txt
  src/templates/template-vision-dcgan/trainers.py
  src/templates/template-vision-dcgan/utils.py
  src/templates/templates.json
Labels: enhancement, templates

#124 chore: add a landing page
  index.html
  package.json
  pnpm-lock.yaml
  public/_redirects
  public/og-image.png
  src/App.vue
  src/assets/code-generator-preview.png
  src/components/Footer.vue
  src/components/NavBar.vue
  src/components/PaneLeft.vue
  src/main.js
  src/views/Create.vue
  src/views/Home.vue
Labels: enhancement

#125 fix: no alpha in message box bg, origin url in dev mode, change instruction for mobile
  src/components/CodeBlock.vue
  src/components/Instruction.vue
  src/components/Message.vue
  src/components/NavBar.vue
  src/store.js
Labels: bug

#126 fix: revert back to previous app UX
  src/components/FormCheckbox.vue
  src/components/FormInput.vue
  src/components/FormRadio.vue
  src/components/TabLoggers.vue
  src/components/TabTraining.vue
  src/metadata/metadata.json
  src/templates/template-common/README.md
  src/templates/template-common/config.yaml
  src/templates/template-vision-classification/README.md
  src/templates/template-vision-classification/config.yaml
  src/templates/template-vision-dcgan/README.md
  src/templates/template-vision-dcgan/config.yaml
Labels: bug

#130 fix(sampler): call set_epoch every epoch start in distributed training
  src/templates/template-vision-classification/main.py
  src/templates/template-vision-dcgan/main.py
Labels: bug, templates

#132 test: run simple and all tests
  .github/workflows/ci.yml
  .gitignore
  .prettierignore
  __tests__/vision-classification.spec.js
  __tests__/vision-dcgan.spec.js
  __tests__/vision-segmentation.spec.js
  jest.config.js
  package.json
  pnpm-lock.yaml
  scripts/download_datasets.py
  scripts/requirements.txt
  scripts/run_tests.sh
  src/components/FormCheckbox.vue
  src/components/FormInput.vue
  src/components/FormRadio.vue
  src/components/FormSelect.vue
  src/templates/template-common/config.yaml
  src/templates/template-vision-classification/config.yaml
  src/templates/template-vision-dcgan/config.yaml
  src/templates/template-vision-segmentation/config.yaml
  src/templates/template-vision-segmentation/trainers.py
Labels: enhancement, test

#135 test: generate zip with full template names
  __tests__/vision-classification.spec.js
  __tests__/vision-dcgan.spec.js
  __tests__/vision-segmentation.spec.js
Labels: bug, templates

#134 fix(template-segmentation): call .step() / attach to engine
  src/templates/template-vision-segmentation/main.py
Labels: bug, templates

#131 feat(templates): port text classification template (WIP)
  __tests__/text-classification.spec.js
  scripts/requirements.txt
  src/templates/template-text-classification/README.md
  src/templates/template-text-classification/config.yaml
  src/templates/template-text-classification/data.py
  src/templates/template-text-classification/main.py
  src/templates/template-text-classification/model.py
  src/templates/template-text-classification/requirements.txt
  src/templates/template-text-classification/test_all.py
  src/templates/template-text-classification/trainers.py
  src/templates/template-text-classification/utils.py
  src/templates/templates.json
Labels: enhancement, templates

#138 fix: empty `store.code` after changing templates
  src/store.js
  src/templates/templates.json
Labels: bug, frontend

#139 fix: padding-right for right-pane-tabs
  src/components/PaneRight.vue
Labels: frontend

#137 fix: address comments from #136
  __tests__/text-classification.spec.js
  __tests__/vision-classification.spec.js
  __tests__/vision-dcgan.spec.js
  __tests__/vision-segmentation.spec.js
  src/components/TabHandlers.vue
  src/metadata/metadata.json
  src/store.js
  src/templates/template-common/main.py
  src/templates/template-common/utils.py
  src/templates/template-text-classification/main.py
  src/templates/template-text-classification/trainers.py
  src/templates/template-text-classification/utils.py
  src/templates/template-vision-classification/main.py
  src/templates/template-vision-classification/trainers.py
  src/templates/template-vision-classification/utils.py
  src/templates/template-vision-dcgan/main.py
  src/templates/template-vision-dcgan/test_all.py
  src/templates/template-vision-dcgan/trainers.py
  src/templates/template-vision-dcgan/utils.py
  src/templates/template-vision-segmentation/main.py
  src/templates/template-vision-segmentation/model.py
  src/templates/template-vision-segmentation/trainers.py
  src/templates/template-vision-segmentation/utils.py
  src/templates/templates.json
Labels: templates

#140 fix: margin 0 on mobile
  src/components/PaneRight.vue
Labels: bug

#141 fix: default value in store, save on mount
  src/components/FormInput.vue
  src/components/TabLoggers.vue
  src/store.js
Labels: bug

#142 chore: upgrade ignite to nightly
  .github/workflows/ci.yml
  src/templates/template-common/main.py
  src/templates/template-common/utils.py
  src/templates/template-text-classification/main.py
  src/templates/template-text-classification/utils.py
  src/templates/template-vision-classification/main.py
  src/templates/template-vision-classification/utils.py
  src/templates/template-vision-dcgan/main.py
  src/templates/template-vision-dcgan/utils.py
  src/templates/template-vision-segmentation/main.py
  src/templates/template-vision-segmentation/utils.py
Labels: ci, dependencies
